/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.text.SimpleDateFormat;
import java.util.Date;


/**
 *
 * @author jeani
 */
public class Menu extends javax.swing.JFrame {
    cadastroAluno ca = new cadastroAluno();
    cadastroProfessor cp = new cadastroProfessor();

    /**
     * Creates new form Menu2
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        quemSomos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ircadastroAluno = new javax.swing.JButton();
        ircadastroProfessor = new javax.swing.JButton();
        lblData = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        menuFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quemSomos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        quemSomos.setForeground(new java.awt.Color(0, 0, 0));
        quemSomos.setText("Quem somos");
        jPanel1.add(quemSomos, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/imagemAluno.jpeg"))); // NOI18N
        jLabel1.setText("Adicionar uma Imagem aqui, aluno com um livro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 490, 350));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("A nossa empresa de consultoria acadêmica é especializada em fornecer\nsuporte personalizado e orientação a estudantes em sua jornada.\nCom uma equipe de professores, estamos comprometidos em ajudar os \nalunos a alcançarem o sucesso acadêmico.\nAlém disso, proporcionamos orientação na elaboração de projetos, trabalhos\ne pesquisas, ajudando os estudantes a aprimorarem suas habilidades de \nlogica de programação, estruturas de dados e analise de dados.\nNossa empresa de consultoria acadêmica está empenhada em ser uma\nparceira confiável e dedicada, guiando os estudantes em direção a um\npercurso educacional bem-sucedido e preprarando-os para um futuro promissor.");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 470, 180));

        ircadastroAluno.setText("Aluno");
        ircadastroAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ircadastroAlunoActionPerformed(evt);
            }
        });
        jPanel1.add(ircadastroAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));

        ircadastroProfessor.setText("Professor");
        ircadastroProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ircadastroProfessorActionPerformed(evt);
            }
        });
        jPanel1.add(ircadastroProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, -1, -1));

        lblData.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblData.setForeground(new java.awt.Color(0, 0, 0));
        lblData.setText("DATA");
        jPanel1.add(lblData, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, 110, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Bem vindo!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 100, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ao nosso aplicativo de consultoria acadêmica");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 280, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Você é aluno ou professor?");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 200, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 160, 140));

        menuFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo.png"))); // NOI18N
        menuFundo.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lacinia auctor ex non suscipit. Vestibulum rutrum euismod nunc, id ultricies risus tincidunt eu. Suspendisse pretium suscipit neque ut iaculis. Etiam elementum ante ut sapien mattis suscipit. Nulla purus mi, vehicula ac ornare in, lacinia eget magna. Cras pretium est velit, non porttitor urna rhoncus id. Phasellus luctus nisl ex, cursus fringilla turpis pellentesque eu. Cras fermentum ipsum vel orci tempus auctor. Duis in posuere urna, eget posuere erat.");
        menuFundo.setMaximumSize(new java.awt.Dimension(1421, 788));
        jPanel1.add(menuFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ircadastroAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ircadastroAlunoActionPerformed
        dispose();
        ca.setVisible(true);
    }//GEN-LAST:event_ircadastroAlunoActionPerformed

    private void ircadastroProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ircadastroProfessorActionPerformed
        dispose();
        cp.setVisible(true);
    }//GEN-LAST:event_ircadastroProfessorActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //data
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        lblData.setText(formato.format(dataSistema));      
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ircadastroAluno;
    private javax.swing.JButton ircadastroProfessor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel menuFundo;
    private javax.swing.JLabel quemSomos;
    // End of variables declaration//GEN-END:variables
}
