/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author jeani
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        Menu login = new Menu();
        new Thread() {
            public void run() {
                try {
                    for (int i = 0; i <= 100; i++) {
                        Thread.sleep(100);
                        telaCarregamento.setValue(i);
                        if (telaCarregamento.getValue() <= 25) {
                            lblStatus.setText("Bem vindo(a) a SoftTech Solutions");
                        } else if (telaCarregamento.getValue() <= 50) {
                            lblStatus.setText("Acessando banco de dados...");
                        } else if (telaCarregamento.getValue() <= 75) {
                            lblStatus.setText("Conectando alunos e professores...");
                        } else if (telaCarregamento.getValue() <= 99) {
                            lblStatus.setText("Tudo pronto.");
                        } else {
                            dispose();
                            login.setVisible(true);
                        }
                    }
                } catch (InterruptedException ex) {
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splashBackground = new javax.swing.JPanel();
        splashLogoEmpresa = new javax.swing.JLabel();
        telaCarregamento = new javax.swing.JProgressBar();
        lblStatus = new javax.swing.JLabel();
        nomeEmpresa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        splashImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splashBackground.setBackground(new java.awt.Color(0, 0, 0));
        splashBackground.setPreferredSize(new java.awt.Dimension(1000, 500));
        splashBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        splashLogoEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.png"))); // NOI18N
        splashBackground.add(splashLogoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 180, 180));

        telaCarregamento.setStringPainted(true);
        splashBackground.add(telaCarregamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 860, 30));

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(0, 0, 0));
        lblStatus.setText("Carregando...");
        splashBackground.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        nomeEmpresa.setBackground(new java.awt.Color(0, 0, 0));
        nomeEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        nomeEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        nomeEmpresa.setText("SoftTech Solutions");
        splashBackground.add(nomeEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Conectando mentes curiosas ao conhecimento do amanhã, com a SoftTech Solutions.");
        splashBackground.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 580, 30));

        splashImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo.png"))); // NOI18N
        splashImage.setMaximumSize(new java.awt.Dimension(1000, 500));
        splashBackground.add(splashImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(splashBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splashBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel nomeEmpresa;
    private javax.swing.JPanel splashBackground;
    private javax.swing.JLabel splashImage;
    private javax.swing.JLabel splashLogoEmpresa;
    private javax.swing.JProgressBar telaCarregamento;
    // End of variables declaration//GEN-END:variables
}
